/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const FundRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const FundRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : FundRequestStatus,
  'screenshotBlobId' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Float64,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'pricePerThousand' : IDL.Float64,
  'serviceType' : IDL.Text,
  'maxQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'apiServiceId' : IDL.Text,
  'category' : IDL.Text,
  'minQuantity' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'userId' : IDL.Principal,
  'link' : IDL.Text,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'serviceId' : IDL.Nat,
  'totalPrice' : IDL.Float64,
  'apiOrderId' : IDL.Opt(IDL.Text),
});
export const TicketStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const SupportTicket = IDL.Record({
  'id' : IDL.Nat,
  'status' : TicketStatus,
  'adminReply' : IDL.Opt(IDL.Text),
  'subject' : IDL.Text,
  'userId' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'approveFundRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSupportTicket' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getBalance' : IDL.Func([], [IDL.Float64], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingFundRequests' : IDL.Func([], [IDL.Vec(FundRequest)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTickets' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SupportTicket)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'adminPlaceOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'rejectFundRequest' : IDL.Func([IDL.Nat], [], []),
  'replyToTicket' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'requestFunds' : IDL.Func([IDL.Float64, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const FundRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const FundRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : FundRequestStatus,
    'screenshotBlobId' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Float64,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'pricePerThousand' : IDL.Float64,
    'serviceType' : IDL.Text,
    'maxQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'apiServiceId' : IDL.Text,
    'category' : IDL.Text,
    'minQuantity' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'userId' : IDL.Principal,
    'link' : IDL.Text,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'serviceId' : IDL.Nat,
    'totalPrice' : IDL.Float64,
    'apiOrderId' : IDL.Opt(IDL.Text),
  });
  const TicketStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const SupportTicket = IDL.Record({
    'id' : IDL.Nat,
    'status' : TicketStatus,
    'adminReply' : IDL.Opt(IDL.Text),
    'subject' : IDL.Text,
    'userId' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'approveFundRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSupportTicket' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getBalance' : IDL.Func([], [IDL.Float64], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingFundRequests' : IDL.Func([], [IDL.Vec(FundRequest)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTickets' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SupportTicket)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'adminPlaceOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'rejectFundRequest' : IDL.Func([IDL.Nat], [], []),
    'replyToTicket' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'requestFunds' : IDL.Func([IDL.Float64, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };