/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FundRequest {
  'id' : bigint,
  'status' : FundRequestStatus,
  'screenshotBlobId' : string,
  'userId' : Principal,
  'timestamp' : Time,
  'amount' : number,
}
export type FundRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'userId' : Principal,
  'link' : string,
  'timestamp' : Time,
  'quantity' : bigint,
  'serviceId' : bigint,
  'totalPrice' : number,
  'apiOrderId' : [] | [string],
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export interface Service {
  'id' : bigint,
  'pricePerThousand' : number,
  'serviceType' : string,
  'maxQuantity' : bigint,
  'name' : string,
  'isActive' : boolean,
  'apiServiceId' : string,
  'category' : string,
  'minQuantity' : bigint,
}
export interface SupportTicket {
  'id' : bigint,
  'status' : TicketStatus,
  'adminReply' : [] | [string],
  'subject' : string,
  'userId' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export type TicketStatus = { 'closed' : null } |
  { 'open' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addService' : ActorMethod<
    [string, string, string, number, bigint, bigint, string],
    undefined
  >,
  'approveFundRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSupportTicket' : ActorMethod<[string, string], undefined>,
  'getBalance' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPendingFundRequests' : ActorMethod<[], Array<FundRequest>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTickets' : ActorMethod<[Principal], Array<SupportTicket>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[bigint, string, bigint], undefined>,
  'adminPlaceOrder' : ActorMethod<[bigint, string, bigint], undefined>,
  'rejectFundRequest' : ActorMethod<[bigint], undefined>,
  'replyToTicket' : ActorMethod<[bigint, string], undefined>,
  'requestFunds' : ActorMethod<[number, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];